#include<stdio.h>
#include<stdlib.h>
int $$state_num=0;
<<<<<<< HEAD
__SearchAndInsert : variable x has been declarated in the frame table.
__SortPrsnt: declaration of variable fail : int x
empty tree string f(int $$Ext,int x){
=======
<<<<<<< HEAD
int main() {
printf("state %d:", $$state_num);
printf("a[5]= [%d,%d,%d,%d,%d]",a[0],a[1],a[2],a[3],a[4]);
printf("y=%d ",y);
printf("\n");
$$state_num++;
printf("state %d:", $$state_num);
printf("a[5]= [%d,%d,%d,%d,%d]",a[0],a[1],a[2],a[3],a[4]);
printf("y=%d ",y);
=======
float  qiujie(int $$Ext,float suanshi[],int n){
float  RValue;
int continue_1;
continue_1=0;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("\n");
$$state_num++;
};
int return_1;
return_1=0;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
if (n==3){float qiujie_1_a;
qiujie_1_a=0;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
int switch_1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
int break_1$;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
break_1$=0;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
switch_1=0;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
int nm_3$;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_3$=%d ",nm_3$);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_3$=%d ",nm_3$);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
nm_3$=(char)(suanshi[1]);
if (nm_3$=='+' || switch_1==1 && break_1$==0 && return_1==0){switch_1=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_3$=%d ",nm_3$);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
return_1=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_3$=%d ",nm_3$);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
RValue=suanshi[0]+suanshi[2];
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_3$=%d ",nm_3$);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_3$=%d ",nm_3$);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
}
;
if (nm_3$=='-' || switch_1==1 && break_1$==0 && return_1==0){switch_1=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_3$=%d ",nm_3$);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
return_1=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_3$=%d ",nm_3$);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
RValue=suanshi[0]-suanshi[2];
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_3$=%d ",nm_3$);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_3$=%d ",nm_3$);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
}
;
if (nm_3$=='*' || switch_1==1 && break_1$==0 && return_1==0){switch_1=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_3$=%d ",nm_3$);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
return_1=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_3$=%d ",nm_3$);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
RValue=suanshi[0]*suanshi[2];
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_3$=%d ",nm_3$);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_3$=%d ",nm_3$);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
}
;
if (nm_3$=='/' || switch_1==1 && break_1$==0 && return_1==0){switch_1=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_3$=%d ",nm_3$);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
return_1=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_3$=%d ",nm_3$);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
RValue=suanshi[0]/suanshi[2];
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_3$=%d ",nm_3$);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("break_1$=%d ",break_1$);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_3$=%d ",nm_3$);
printf("qiujie_1_a=%f ",qiujie_1_a);
printf("return_1=%d ",return_1);
printf("switch_1=%d ",switch_1);
printf("\n");
$$state_num++;
};
}
;
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
}
;
if (return_1==0){float qiujie_pq;
qiujie_pq='0';
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_pq=%f ",qiujie_pq);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
float *qiujie_p;
qiujie_p=&qiujie_pq;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
float *qiujie_q;
qiujie_q=&qiujie_pq;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
int qiujie_k;
qiujie_k=0;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
float qiujie_suanshi1[8]={'0'};
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
int qiujie_s;
qiujie_s=0;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
float qiujie_sum;
qiujie_sum=0;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
continue_1=0;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
int qiujie_m;
qiujie_m=0;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
while(qiujie_m<n){continue_1=0;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
if (suanshi[qiujie_m]=='('){if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_k=qiujie_k+1;
if (*qiujie_p!='('){if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_p=&suanshi[qiujie_m];
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
}
;
continue_1=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_m=qiujie_m+1;
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
}
;
if (continue_1==0){if (suanshi[qiujie_m]==')'){if (qiujie_k==1){if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_k=qiujie_k-1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_suanshi1[qiujie_s]=qiujie(0,qiujie_p+1,qiujie_q-qiujie_p-1);
qiujie_q=&suanshi[qiujie_m];
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_s=qiujie_s+1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_p=&qiujie_pq;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_q=&qiujie_pq;
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_k=qiujie_k-1;
}
;
continue_1=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_m=qiujie_m+1;
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
}
;
if (continue_1==0){if (qiujie_k==0){if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_suanshi1[qiujie_s]=suanshi[qiujie_m];
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_s=qiujie_s+1;
continue_1=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_m=qiujie_m+1;
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
}
;
if (continue_1==0){if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_m=qiujie_m+1;
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
}
;
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
}
;
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
}
;
}
;
continue_1=0;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
if (qiujie_s==3){qiujie_sum=qiujie(0,qiujie_suanshi1,qiujie_s);
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_p=&qiujie_suanshi1[0];
>>>>>>> 1f4c235c2433c82837b26242c91144349a1d5abc
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
<<<<<<< HEAD
}
int main() {
int x;
printf("state %d:", $$state_num);
=======
qiujie_q=&qiujie_suanshi1[2];
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_m=0;
while(qiujie_m<(qiujie_s-1)/2){break_1$=0;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
switch_1=0;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
int nm_4$;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
nm_4$=(char)(qiujie_suanshi1[2*qiujie_m+1]);
if (nm_4$=='+' || switch_1==1 && break_1$==0 && return_1==0){switch_1=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
if ((qiujie_s-1)/2!=1 && qiujie_suanshi1[2*(2)+1]=='*' || qiujie_suanshi1[2*(2)+1]=='/'){*qiujie_q=qiujie(0,qiujie_p+2,3);
int qiujie_9_10_11_ws;
qiujie_9_10_11_ws=&qiujie_suanshi1[qiujie_s-1]-&qiujie_suanshi1[2*(2)];
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_9_10_11_ws=%d ",qiujie_9_10_11_ws);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
int qiujie_9_10_11_w;
qiujie_9_10_11_w=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_9_10_11_w=%d ",qiujie_9_10_11_w);
printf("qiujie_9_10_11_ws=%d ",qiujie_9_10_11_ws);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
while(qiujie_9_10_11_w<=qiujie_9_10_11_ws){if (qiujie_q+qiujie_9_10_11_w+2-qiujie_q+qiujie_9_10_11_ws>0){if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_9_10_11_w=%d ",qiujie_9_10_11_w);
printf("qiujie_9_10_11_ws=%d ",qiujie_9_10_11_ws);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
*qiujie_q+qiujie_9_10_11_w=-1;
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_9_10_11_w=%d ",qiujie_9_10_11_w);
printf("qiujie_9_10_11_ws=%d ",qiujie_9_10_11_ws);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
*qiujie_q+qiujie_9_10_11_w=*qiujie_q+qiujie_9_10_11_w+2;
}
;
if(!$$Ext){printf("state %d:", $$state_num);
>>>>>>> 1f4c235c2433c82837b26242c91144349a1d5abc
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_9_10_11_w=%d ",qiujie_9_10_11_w);
printf("qiujie_9_10_11_ws=%d ",qiujie_9_10_11_ws);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
<<<<<<< HEAD
f(1,x);
=======
};
qiujie_9_10_11_w=qiujie_9_10_11_w+1;
}
;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_9_10_11_w=%d ",qiujie_9_10_11_w);
printf("qiujie_9_10_11_ws=%d ",qiujie_9_10_11_ws);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_s=qiujie_s-2;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_9_10_11_w=%d ",qiujie_9_10_11_w);
printf("qiujie_9_10_11_ws=%d ",qiujie_9_10_11_ws);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_m=qiujie_m-1;
} else {if (qiujie_m==0){if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_sum=qiujie_sum+*qiujie_p+*qiujie_q;
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_sum=qiujie_sum+*qiujie_q;
}
;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_p=qiujie_p+2;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_q=qiujie_q+2;
}
;
break_1$=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
}
;
if (nm_4$=='-' || switch_1==1 && break_1$==0 && return_1==0){switch_1=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
if ((qiujie_s-1)/2!=1 && qiujie_suanshi1[2*(2)+1]=='*' || qiujie_suanshi1[2*(2)+1]=='/'){*qiujie_q=qiujie(0,qiujie_p+2,3);
int qiujie_9_10_17_ws;
qiujie_9_10_17_ws=&qiujie_suanshi1[qiujie_s-1]-&qiujie_suanshi1[2*(2)];
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_9_10_17_ws=%d ",qiujie_9_10_17_ws);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
int qiujie_9_10_17_w;
qiujie_9_10_17_w=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_9_10_17_w=%d ",qiujie_9_10_17_w);
printf("qiujie_9_10_17_ws=%d ",qiujie_9_10_17_ws);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
while(qiujie_9_10_17_w<=qiujie_9_10_17_ws){if (qiujie_q+qiujie_9_10_17_w+2-qiujie_q+qiujie_9_10_17_ws>0){if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_9_10_17_w=%d ",qiujie_9_10_17_w);
printf("qiujie_9_10_17_ws=%d ",qiujie_9_10_17_ws);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
*qiujie_q+qiujie_9_10_17_w=-1;
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_9_10_17_w=%d ",qiujie_9_10_17_w);
printf("qiujie_9_10_17_ws=%d ",qiujie_9_10_17_ws);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
*qiujie_q+qiujie_9_10_17_w=*qiujie_q+qiujie_9_10_17_w+2;
}
;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_9_10_17_w=%d ",qiujie_9_10_17_w);
printf("qiujie_9_10_17_ws=%d ",qiujie_9_10_17_ws);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_9_10_17_w=qiujie_9_10_17_w+1;
}
;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_9_10_17_w=%d ",qiujie_9_10_17_w);
printf("qiujie_9_10_17_ws=%d ",qiujie_9_10_17_ws);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_s=qiujie_s-2;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_9_10_17_w=%d ",qiujie_9_10_17_w);
printf("qiujie_9_10_17_ws=%d ",qiujie_9_10_17_ws);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_m=-1;
} else {if (qiujie_m==0){if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_sum=qiujie_sum+*qiujie_p-*qiujie_q;
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_sum=qiujie_sum-*qiujie_q;
}
;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_p=qiujie_p+2;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_q=qiujie_q+2;
}
;
break_1$=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
}
;
if (nm_4$=='*' || switch_1==1 && break_1$==0 && return_1==0){switch_1=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
if (qiujie_m==0){if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_sum=qiujie_sum+*qiujie_p**qiujie_q;
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_sum=qiujie_sum**qiujie_q;
}
;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_p=qiujie_p+2;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_q=qiujie_q+2;
break_1$=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
}
;
if (nm_4$=='/' || switch_1==1 && break_1$==0 && return_1==0){switch_1=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
if (qiujie_m==0){if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_sum=qiujie_sum+*qiujie_p/*qiujie_q;
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_sum=qiujie_sum/*qiujie_q;
}
;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_p=qiujie_p+2;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_q=qiujie_q+2;
break_1$=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
}
;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
qiujie_m=qiujie_m+1;
}
;
}
;
return_1=1;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
RValue=qiujie_sum;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("nm_4$=%d ",nm_4$);
printf("qiujie_k=%d ",qiujie_k);
printf("qiujie_m=%d ",qiujie_m);
printf("qiujie_p=%p ",qiujie_p);
printf("qiujie_pq=%f ",qiujie_pq);
printf("qiujie_q=%p ",qiujie_q);
printf("qiujie_s=%d ",qiujie_s);
printf("qiujie_suanshi1[8]= [%f,%f,%f,%f,%f,%f,%f,%f]",qiujie_suanshi1[0],qiujie_suanshi1[1],qiujie_suanshi1[2],qiujie_suanshi1[3],qiujie_suanshi1[4],qiujie_suanshi1[5],qiujie_suanshi1[6],qiujie_suanshi1[7]);
printf("qiujie_sum=%f ",qiujie_sum);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
} else {if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
}
;
if(!$$Ext){printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("RValue=%f ",RValue);
printf("continue_1=%d ",continue_1);
printf("n=%d ",n);
printf("return_1=%d ",return_1);
printf("\n");
$$state_num++;
};
return RValue;
}

int main() {
int x;
x=1;
>>>>>>> 1f4c235c2433c82837b26242c91144349a1d5abc
printf("state %d:", $$state_num);
printf("x=%d ",x);
printf("\n");
$$state_num++;
printf("state %d:", $$state_num);
printf("x=%d ",x);
>>>>>>> 54d3951519e27444f35b98893213a6906431404b
printf("\n");
$$state_num++;
return 0;
}
