#line 2 "lex.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 114
#define YY_END_OF_BUFFER 115
static yyconst short int yy_accept[297] =
    {   0,
        0,    0,    0,    0,  115,  109,  108,  107,   61,  109,
       83,   68,   42,  109,   76,   77,   66,   64,   82,   65,
       52,   67,  100,  100,   17,   41,   56,   53,   57,   99,
       99,   99,   78,   79,   69,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   80,   87,   81,   72,  110,
      111,  110,  110,  108,   60,    0,  103,    0,    0,    0,
       74,    1,  106,   63,  104,  100,    0,    0,   55,    0,
       62,   70,   58,   73,   59,   71,   99,   99,   99,   99,
       96,   99,   99,   99,   99,   99,   99,   33,   99,   99,

       99,   99,   99,   99,   99,   99,   99,   99,   99,   27,
       99,   99,   99,   99,   99,   88,   99,    3,   99,   84,
       99,   99,   99,   99,   86,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,    9,  113,    0,
      103,    0,    0,  105,  105,  104,  101,    0,  102,   75,
       54,   99,   99,   15,    2,   99,   99,   90,   99,   99,
       99,   99,   99,   99,   99,    5,   99,   30,   99,   99,
       94,   99,   99,   43,   99,   25,   99,   99,   99,   99,
       99,   99,   10,   99,   93,   99,   99,   99,   99,   99,
       99,   16,   99,   99,   99,   99,   99,   99,   99,   99,

       99,   99,   85,  112,   50,   95,   99,   46,   99,   99,
       29,   99,   99,   99,   99,   99,   99,   99,    7,   99,
       14,   48,   13,   11,   99,   99,   99,   89,   99,   99,
       99,   91,   99,    4,   99,   99,   28,   99,   23,   99,
       99,   99,   49,   99,   99,    8,   99,   99,    6,   99,
       99,   24,   47,   26,   99,   38,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   31,   22,   99,   35,   99,
       32,   19,   99,   18,   51,   99,   37,   99,   40,   99,
       34,   99,   97,   44,   21,   99,   12,   36,   99,   45,
       92,   39,   99,   20,   98,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   28,
       29,   29,   30,   29,   29,   31,   29,   32,   33,   29,
       29,   29,   29,   29,   34,   29,   29,   35,   29,   29,
       36,   37,   38,   39,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
       65,   29,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[70] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        1,    1,    1,    1,    1,    4,    4,    4,    2,    2,
        2,    2,    2,    2,    2,    1,    1,    1,    1,    2,
        4,    4,    4,    4,    4,    4,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[302] =
    {   0,
        0,    0,   67,   68,  205,  912,  195,  912,  171,   67,
      912,  912,  912,  155,  912,  912,  912,  912,  912,  162,
      912,   60,   57,   67,  150,  912,   73,  134,   58,   79,
       81,   86,  115,  912,  912,   88,   90,   94,  103,  105,
       96,  107,   98,  113,  116,  109,  149,  151,  153,  159,
      171,  169,  156,  164,  181,  912,   80,  912,  912,  912,
      912,  119,  101,  129,  912,  125,  912,  218,  109,  228,
      912,  912,  912,  912,  161,  179,    0,  216,  912,   78,
      912,  912,   69,  912,  912,  912,  166,  183,  220,  222,
      912,  224,  229,  226,  238,  243,  249,  261,  271,  277,

      274,  279,  281,  283,  285,  287,  290,  292,  294,  296,
      298,  300,  302,  305,  307,  317,  320,  322,  328,  330,
      340,  342,  347,  352,  349,  356,  354,  362,  359,  366,
      371,  374,  379,  383,  385,  394,  398,   23,  912,   60,
      140,  145,  416,  912,   69,  400,    0,  417,  403,  912,
      912,  419,  410,  430,  432,  436,  440,  444,  446,  448,
      452,  458,  460,  462,  467,  469,  471,  473,  480,  482,
      486,  489,  491,  494,  497,  501,  503,  509,  511,  516,
      519,  521,  523,  525,  527,  531,  536,  538,  540,  542,
      545,  550,  555,  558,  560,  563,  566,  568,  570,  574,

      578,  572,  912,  912,  583,  587,  590,  594,  606,  609,
      611,  613,  615,  618,  620,  622,  624,  626,  628,  632,
      634,  636,  638,  643,  647,  651,  653,  660,  664,  668,
      670,  674,  676,  678,  680,  684,  686,  697,  699,  703,
      705,  709,  711,  713,  717,  719,  721,  723,  725,  727,
      729,  731,  734,  739,  748,  750,  752,  754,  756,  759,
      762,  765,  769,  771,  773,  775,  781,  783,  785,  787,
      789,  791,  795,  797,  806,  808,  810,  812,  815,  819,
      821,  823,  825,  829,  831,  833,  835,  837,  839,  842,
      846,  848,  852,  854,  856,  912,  896,  900,  904,  907,

       71
    } ;

static yyconst short int yy_def[302] =
    {   0,
      296,    1,  297,  297,  296,  296,  296,  296,  296,  298,
      296,  296,  296,  299,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  300,
      300,  300,  296,  296,  296,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  298,  296,  298,  296,  296,
      296,  296,  296,  296,  296,  296,  301,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  300,  300,  300,  300,
      296,  300,  300,  300,  300,  300,  300,  300,  300,  300,

      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  296,  296,  296,
      298,  298,  298,  296,  296,  296,  301,  296,  296,  296,
      296,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,

      300,  300,  296,  296,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,    0,  296,  296,  296,  296,

      296
    } ;

static yyconst short int yy_nxt[982] =
    {   0,
        6,    7,    8,    9,   10,   11,    6,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   30,   31,   30,   30,
       30,   32,   30,   30,   30,   33,    6,   34,   35,   30,
       36,   30,   37,   38,   39,   40,   41,   42,   43,   30,
       44,   45,   46,   47,   48,   49,   30,   50,   51,   52,
       53,   54,   55,   30,   30,   56,   57,   58,   59,   61,
       61,   67,   72,   75,  147,   76,   76,   73,  144,   62,
       62,   85,   86,   75,   74,   76,   76,  204,   80,  203,
       81,   77,  151,   63,   63,   82,   83,   88,   88,   88,

       88,   78,  150,   68,   88,   88,   88,   88,   88,   88,
       89,   78,   88,   88,   88,   88,   88,   88,  144,   90,
       77,   88,   88,   88,   88,   88,   88,   88,   88,   67,
       64,   88,   88,  140,   88,   88,  139,   95,   96,   92,
      108,   93,   97,  110,   67,  102,  138,  109,   98,   67,
       94,  111,   91,  103,   99,  100,  104,  112,   84,  105,
      113,   68,  106,  115,  114,  107,  101,   88,   88,   88,
       88,   88,   88,   79,   88,   88,   68,   88,   88,  146,
      146,   68,   88,   88,   88,   88,   71,   88,   88,   88,
       88,   70,  116,  117,   65,   75,   64,   76,   76,   88,

       88,   88,   88,  124,  296,   78,  296,  121,  118,  134,
      122,  119,  120,  123,  125,  126,  131,  132,  135,  127,
      136,  128,  141,   78,  296,  129,  133,  142,  137,  148,
      130,  148,   69,  296,  149,  149,  142,  145,   88,   88,
       88,   88,   88,   88,   88,   88,   69,   88,   88,  296,
      152,  296,  153,  296,  143,  296,   88,   88,  296,  142,
      296,   88,   88,  142,   69,  296,  156,   88,   88,   69,
      296,  142,  155,   69,  296,  142,  296,  142,  157,   88,
       88,   69,  148,  296,  142,   69,  154,   69,  159,   88,
       88,  158,   88,   88,   69,   88,   88,   88,   88,   88,

       88,   88,   88,   88,   88,   88,   88,  160,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,  163,   88,   88,   88,   88,  169,  296,  161,
      165,  296,  162,  164,  166,   88,   88,  167,   88,   88,
       88,   88,  168,  170,  175,  172,   88,   88,   88,   88,
      296,  171,  296,  173,  296,  176,  296,  174,   88,   88,
       88,   88,  296,  177,  178,   88,   88,   88,   88,  296,
       88,   88,   88,   88,   88,   88,  296,   88,   88,  296,
       88,   88,  296,  179,   88,   88,  182,  180,  181,   88,
       88,  183,   88,   88,  186,  296,  184,   88,   88,  296,

      190,   88,   88,   88,   88,  296,  185,  187,  188,  189,
      191,  192,   88,   88,  296,  194,   88,   88,  146,  146,
      141,  149,  149,  193,  296,  142,  195,  296,   88,   88,
      148,  197,  148,  200,  142,  149,  149,   88,   88,  196,
      206,  198,  199,  296,   78,  205,  202,  201,   88,   88,
       88,   88,  143,  296,   88,   88,  296,  142,   88,   88,
      296,  142,   88,   88,   88,   88,   88,   88,  296,  142,
       88,   88,  296,  142,  296,  142,   88,   88,   88,   88,
       88,   88,  142,  148,  207,   88,   88,   88,   88,   88,
       88,   88,   88,  296,  209,  296,  211,  208,   88,   88,

       88,   88,  296,  210,   88,   88,  214,   88,   88,   88,
       88,  216,   88,   88,  296,   88,   88,  212,  213,   88,
       88,   88,   88,  296,  218,  215,  296,   88,   88,   88,
       88,  296,  217,  296,   88,   88,  296,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,  296,  219,   88,
       88,  220,  221,  223,   88,   88,   88,   88,   88,   88,
       88,   88,  222,   88,   88,  296,  227,  228,   88,   88,
      224,  225,  226,   88,   88,  229,   88,   88,   88,   88,
      230,   88,   88,  232,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,  296,  233,   88,   88,  231,  296,

      234,   88,   88,  235,  238,   88,   88,  239,   88,   88,
      296,  237,   88,   88,  296,  236,  241,  243,  242,  296,
      240,  296,  244,  245,   88,   88,  296,   88,   88,   88,
       88,   88,   88,   88,   88,  296,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,  296,  246,
       88,   88,   88,   88,   88,   88,   88,   88,  296,  247,
      248,   88,   88,  296,  252,   88,   88,  296,  254,   88,
       88,   88,   88,  296,  250,  251,  296,  249,   88,   88,
      296,  253,   88,   88,  296,  255,   88,   88,   88,   88,
      296,  256,   88,   88,   88,   88,   88,   88,   88,   88,

      296,  259,   88,   88,   88,   88,  296,  257,  261,  296,
      258,  296,  260,  296,  262,   88,   88,   88,   88,  296,
      263,   88,   88,   88,   88,  296,  265,   88,   88,   88,
       88,   88,   88,  264,  296,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,  268,   88,   88,  296,  266,  267,   88,   88,  296,
      269,  271,  296,  273,  296,  272,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,  270,   88,   88,  296,
       88,   88,  275,   88,   88,  274,  296,   88,   88,   88,
       88,   88,   88,   88,   88,  296,  276,  296,  278,   88,

       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,  277,  283,   88,   88,   88,   88,  284,  296,  279,
      280,  281,  296,  282,   88,   88,   88,   88,   88,   88,
       88,   88,  285,   88,   88,  296,  286,   88,   88,   88,
       88,   88,   88,   88,   88,  296,  287,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,  288,
       88,   88,  289,  291,   88,   88,   88,   88,  296,  290,
       88,   88,   88,   88,   88,   88,  296,  293,  296,  296,
      296,  296,  292,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  294,  296,  296,  295,   60,   60,   60,   60,

       66,   66,   66,   66,   69,   69,  296,   69,   87,  296,
       87,    5,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296
    } ;

static yyconst short int yy_chk[982] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,   10,   22,   23,  301,   23,   23,   22,  145,    3,
        4,   29,   29,   24,   22,   24,   24,  140,   27,  138,
       27,   23,   83,    3,    4,   27,   27,   30,   30,   31,

       31,   23,   80,   10,   32,   32,   36,   36,   37,   37,
       31,   24,   38,   38,   41,   41,   43,   43,   69,   32,
       23,   39,   39,   40,   40,   42,   42,   46,   46,   66,
       64,   44,   44,   63,   45,   45,   62,   37,   38,   36,
       41,   36,   38,   43,  141,   40,   57,   42,   38,  142,
       36,   43,   33,   40,   39,   39,   40,   44,   28,   40,
       45,   66,   40,   46,   45,   40,   39,   47,   47,   48,
       48,   49,   49,   25,   53,   53,  141,   50,   50,   75,
       75,  142,   54,   54,   87,   87,   20,   52,   52,   51,
       51,   14,   47,   47,    9,   76,    7,   76,   76,   55,

       55,   88,   88,   50,    5,   75,    0,   49,   48,   53,
       49,   48,   48,   49,   50,   51,   52,   52,   54,   51,
       55,   51,   68,   76,    0,   51,   52,   68,   55,   78,
       51,   78,   70,    0,   78,   78,   68,   70,   89,   89,
       90,   90,   92,   92,   94,   94,   70,   93,   93,    0,
       89,    0,   90,    0,   68,    0,   95,   95,    0,   68,
        0,   96,   96,   68,   70,    0,   94,   97,   97,   70,
        0,   68,   93,   70,    0,   68,    0,   68,   95,   98,
       98,   70,   78,    0,   68,   70,   92,   70,   96,   99,
       99,   95,  101,  101,   70,  100,  100,  102,  102,  103,

      103,  104,  104,  105,  105,  106,  106,   97,  107,  107,
      108,  108,  109,  109,  110,  110,  111,  111,  112,  112,
      113,  113,  101,  114,  114,  115,  115,  106,    0,   99,
      102,    0,  100,  101,  103,  116,  116,  104,  117,  117,
      118,  118,  105,  107,  112,  109,  119,  119,  120,  120,
        0,  108,    0,  111,    0,  113,    0,  111,  121,  121,
      122,  122,    0,  114,  115,  123,  123,  125,  125,    0,
      124,  124,  127,  127,  126,  126,    0,  129,  129,    0,
      128,  128,    0,  117,  130,  130,  122,  119,  121,  131,
      131,  122,  132,  132,  124,    0,  122,  133,  133,    0,

      127,  134,  134,  135,  135,    0,  123,  124,  124,  126,
      128,  129,  136,  136,    0,  131,  137,  137,  146,  146,
      143,  149,  149,  130,    0,  143,  132,    0,  153,  153,
      148,  134,  148,  135,  143,  148,  148,  152,  152,  133,
      153,  134,  134,    0,  146,  152,  137,  136,  154,  154,
      155,  155,  143,    0,  156,  156,    0,  143,  157,  157,
        0,  143,  158,  158,  159,  159,  160,  160,    0,  143,
      161,  161,    0,  143,    0,  143,  162,  162,  163,  163,
      164,  164,  143,  148,  156,  165,  165,  166,  166,  167,
      167,  168,  168,    0,  159,    0,  161,  157,  169,  169,

      170,  170,    0,  160,  171,  171,  164,  172,  172,  173,
      173,  167,  174,  174,    0,  175,  175,  162,  163,  176,
      176,  177,  177,    0,  170,  165,    0,  178,  178,  179,
      179,    0,  169,    0,  180,  180,    0,  181,  181,  182,
      182,  183,  183,  184,  184,  185,  185,    0,  172,  186,
      186,  173,  175,  178,  187,  187,  188,  188,  189,  189,
      190,  190,  177,  191,  191,    0,  182,  184,  192,  192,
      179,  180,  181,  193,  193,  186,  194,  194,  195,  195,
      187,  196,  196,  189,  197,  197,  198,  198,  199,  199,
      202,  202,  200,  200,    0,  190,  201,  201,  188,    0,

      191,  205,  205,  193,  195,  206,  206,  196,  207,  207,
        0,  194,  208,  208,    0,  193,  198,  200,  199,    0,
      197,    0,  201,  202,  209,  209,    0,  210,  210,  211,
      211,  212,  212,  213,  213,    0,  214,  214,  215,  215,
      216,  216,  217,  217,  218,  218,  219,  219,    0,  207,
      220,  220,  221,  221,  222,  222,  223,  223,    0,  209,
      210,  224,  224,    0,  215,  225,  225,    0,  217,  226,
      226,  227,  227,    0,  213,  214,    0,  212,  228,  228,
        0,  216,  229,  229,    0,  218,  230,  230,  231,  231,
        0,  220,  232,  232,  233,  233,  234,  234,  235,  235,

        0,  227,  236,  236,  237,  237,    0,  225,  230,    0,
      226,    0,  229,    0,  231,  238,  238,  239,  239,    0,
      233,  240,  240,  241,  241,    0,  236,  242,  242,  243,
      243,  244,  244,  235,    0,  245,  245,  246,  246,  247,
      247,  248,  248,  249,  249,  250,  250,  251,  251,  252,
      252,  241,  253,  253,    0,  238,  240,  254,  254,    0,
      242,  245,    0,  248,    0,  247,  255,  255,  256,  256,
      257,  257,  258,  258,  259,  259,  244,  260,  260,    0,
      261,  261,  251,  262,  262,  250,    0,  263,  263,  264,
      264,  265,  265,  266,  266,    0,  255,    0,  258,  267,

      267,  268,  268,  269,  269,  270,  270,  271,  271,  272,
      272,  257,  263,  273,  273,  274,  274,  264,    0,  259,
      260,  261,    0,  262,  275,  275,  276,  276,  277,  277,
      278,  278,  265,  279,  279,    0,  268,  280,  280,  281,
      281,  282,  282,  283,  283,    0,  270,  284,  284,  285,
      285,  286,  286,  287,  287,  288,  288,  289,  289,  273,
      290,  290,  276,  280,  291,  291,  292,  292,    0,  278,
      293,  293,  294,  294,  295,  295,    0,  286,    0,    0,
        0,    0,  282,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  289,    0,    0,  293,  297,  297,  297,  297,

      298,  298,  298,  298,  299,  299,    0,  299,  300,    0,
      300,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "MSV.l"
#define INITIAL 0
#line 2 "MSV.l"
#include "function.h"
#include <string.h> // strcpy, strncpy
#include <math.h>
#include <io.h>     // isatty.h>
#include "MyMap.h"
#include "SyntaxNode.h"




extern CMAP g_StructNameMap;
int lineno=1;

// For some reason isatty is called _isatty in Visual C++
#ifdef MSVC
#define isatty _isatty
#endif

// Forward declarations for include files
class CSyntaxNode;
class Symbol;
class SymbolTable;

// Make sure our variables get created
#define  _LEX_CPP_
//#include "lex.h"
//#include "lexSymbol.h"
#include "parse.cpp.h"

// The yywrap and error functions are declared by the caller
extern "C" int yywrap();
extern void error( char *cFormat, ... );
extern 

void DeleteSingleLineComment (void);
void passStringConstant (void);

#define comment 1

/*
\b 退格
\f 走纸换页
\n 换行
\r 回车
\t 横向跳格 (Ctrl-I)
\' 单引号
\" 双引号
\\反斜杠
*/
#line 730 "lex.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 68 "MSV.l"


#line 880 "lex.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 297 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 912 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 70 "MSV.l"
BEGIN comment;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 72 "MSV.l"
{return AND;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 73 "MSV.l"
{return OR;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 74 "MSV.l"
{return SKIP;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 75 "MSV.l"
{return FINAL;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 76 "MSV.l"
{return EMPTY;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 77 "MSV.l"
{return HALT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 78 "MSV.l"
{return AWAIT;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 79 "MSV.l"
{return PARALLEL;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 80 "MSV.l"
{return PROJECTION;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 81 "MSV.l"
{return NEXT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 82 "MSV.l"
{return W_NEXT;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 83 "MSV.l"
{return MORE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 84 "MSV.l"
{return KEEP;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 85 "MSV.l"
{return ALWAYS;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 86 "MSV.l"
{return SOMETIMES;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 87 "MSV.l"
{return COLON;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 88 "MSV.l"
{return EXIST;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 89 "MSV.l"
{return DEFINE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 90 "MSV.l"
{return FUNCTION;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 91 "MSV.l"
{return STRUCT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 92 "MSV.l"
{return UNION;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 93 "MSV.l"
{return MY_TRUE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 94 "MSV.l"
{return MY_FALSE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 96 "MSV.l"
{return LENGTH;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 97 "MSV.l"
{return FRAME;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 98 "MSV.l"
{return IF;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 99 "MSV.l"
{return THEN;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 100 "MSV.l"
{return ELSE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 101 "MSV.l"
{return FOR;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 102 "MSV.l"
{return TIMES;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 103 "MSV.l"
{return WHILE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 104 "MSV.l"
{return DO;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 105 "MSV.l"
{return REPEAT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 106 "MSV.l"
{return UNTIL;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 107 "MSV.l"
{return DISPLAY;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 108 "MSV.l"
{return DISPLAY;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 109 "MSV.l"
{return REQUEST;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 110 "MSV.l"
{return REQUEST;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 111 "MSV.l"
{return PREFIX;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 113 "MSV.l"
{return CHOP;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 114 "MSV.l"
{return ADDRESS;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 116 "MSV.l"
{return INTDECLARATION;}//  added by Jane 2012-05-21
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 117 "MSV.l"
{return STRDECLARATION;}//STRVARIABLE  added by Jane 2012-05-21
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 118 "MSV.l"
{return POINTERDECLARATION;}//POINTER  added by Jane 2012-05-21
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 119 "MSV.l"
{return CHARDECLARATION;}//CHARVARIABLE  added by Jane 2012-05-21 
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 120 "MSV.l"
{return FLOATDECLARATION;}//FLOATVARIABLE  added by Jane 2012-05-21
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 121 "MSV.l"
{return LISTDECLARATION;}//LISTVARIABLE  added by Jane 2012-05-21
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 122 "MSV.l"
{return VOIDDECLARATION;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 125 "MSV.l"
{return FILEDECLARATION;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 126 "MSV.l"
{return EXTERN;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 129 "MSV.l"
{return DOT;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 130 "MSV.l"
{return EQ;}     //比较相等符号 “=”
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 131 "MSV.l"
{return ASS_P;}   //赋值符号已修改为“<==”
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 133 "MSV.l"
{return ASS_N;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 135 "MSV.l"
{return LT;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 136 "MSV.l"
{return GT;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 137 "MSV.l"
{return LE;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 138 "MSV.l"
{return GE;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 139 "MSV.l"
{return NE;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 140 "MSV.l"
{return NEGATION;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 141 "MSV.l"
{return PBEGIN;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 142 "MSV.l"
{return PEND;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 144 "MSV.l"
{return ADD;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 145 "MSV.l"
{return SUB;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 146 "MSV.l"
{return MUL;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 147 "MSV.l"
{return DIV;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 148 "MSV.l"
{return MOD;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 149 "MSV.l"
{return CON;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 150 "MSV.l"
{return LST;}//左移 left shift
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 151 "MSV.l"
{return RST;}//右移 right shift
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 152 "MSV.l"
{return BNE;}//按位非 bit negation
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 154 "MSV.l"
{return PROPIMPLY;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 155 "MSV.l"
{return IMPLY;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 156 "MSV.l"
{return IFF;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 158 "MSV.l"
{return OPEN_PAR;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 159 "MSV.l"
{return CLOSE_PAR;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 160 "MSV.l"
{return OPEN_MPAR;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 161 "MSV.l"
{return CLOSE_MPAR;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 162 "MSV.l"
{return OPEN_BPAR;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 163 "MSV.l"
{return CLOSE_BPAR;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 164 "MSV.l"
{return COMMA;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 165 "MSV.l"
{return CHOPSTAR;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 168 "MSV.l"
{return OVER;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 169 "MSV.l"
{return CYLINDER;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 170 "MSV.l"
{return OVEREP;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 172 "MSV.l"
{return	INTER_OR;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 173 "MSV.l"
{return NON_DETERMINED;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 175 "MSV.l"
{return PROCESS;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 176 "MSV.l"
{return CHANNEL;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 177 "MSV.l"
{return SEND;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 178 "MSV.l"
{return RECEIVE;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 179 "MSV.l"
{return PUT;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 180 "MSV.l"
{return GET;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 182 "MSV.l"
{return POINTERNULL;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 183 "MSV.l"
{return ARRAY;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 185 "MSV.l"
{return SIGNED;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 186 "MSV.l"
{return UNSIGNED;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 190 "MSV.l"
{
			   yylval.cString=new char[strlen(yytext)+1];
			   strcpy(yylval.cString,yytext);
               
			   if(!g_StructNameMap.find(yytext))
			   {
			       return ID;
			   }
			   else
			   {
                   return STRUCT_TYPE;
			   }
		}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 203 "MSV.l"
{    
               yylval.nInteger=atoi(yytext);
               return INTLITERAL;
		 }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 207 "MSV.l"
{    
               int decValue;//int，保存16进制对应的十进制数
			   sscanf(yytext,"%x",&decValue);//将16进制字符串转成10进制数
			   yylval.nInteger=decValue;//将10进制数赋给yytext
               return INTLITERAL;
			}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 213 "MSV.l"
{
               char* result=NULL;
			   result=strtok(yytext, "e");
			   int iVal;
			   float fVal;
			   sscanf(result, "%f", &fVal);
			   while(result!=NULL)
			   {
			      sscanf(result, "%d", &iVal);
				  result = strtok(NULL, "e");
				}

               yylval.floatval = fVal*pow(10, iVal); 
			   return FLOATLITERAL;
			}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 228 "MSV.l"
{
               passStringConstant ();
			   return STRLITERAL;
         }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 233 "MSV.l"
{		
				yylval. floatval = atof(yytext); 
				return FLOATLITERAL; 
		 }//Added by Jane 2012-05-21 
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 237 "MSV.l"
{//modified by yubin 2014/2/25，第一个if分支处理没有转义字符的情况，下面的分支处理有转义字符的情况
				if(yytext[1]!='\\')
				{
					yylval.character=yytext[1];
					return CHARLITERAL;
				}
				else if(yytext[2]=='n')
				{
					yylval.character='\n';
					return CHARLITERAL;
				}
				else if(yytext[2]=='b')
				{
					yylval.character='\b';
					return CHARLITERAL;
				}
				else if(yytext[2]=='f')
				{
					yylval.character='\f';
					return CHARLITERAL;
				}
				else if(yytext[2]=='r')
				{
					yylval.character='\r';
					return CHARLITERAL;
				}
				else if(yytext[2]=='t')
				{
					yylval.character='\t';
					return CHARLITERAL;
				}
				else if(yytext[2]=='\'')
				{
					yylval.character='\'';
					return CHARLITERAL;
				}
				else if(yytext[2]=='\"')
				{
					yylval.character='\"';
					return CHARLITERAL;
				}
				else if(yytext[2]=='\\')
				{
					yylval.character='\\';
					return CHARLITERAL;
				}
				else if(yytext[2]=='0')
				{
					yylval.character='\0';
					return CHARLITERAL;
				}
		}   //2013-4-22 add by YY[fixed]
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 292 "MSV.l"
{DeleteSingleLineComment();}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 293 "MSV.l"
{++lineno;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 294 "MSV.l"
{}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 295 "MSV.l"
{return ERROR_TOKEN;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 297 "MSV.l"
{}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 298 "MSV.l"
{++lineno;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 299 "MSV.l"
{error("EOF in comment");}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 300 "MSV.l"
{BEGIN 0;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 302 "MSV.l"
ECHO;
	YY_BREAK
#line 1624 "lex.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 297 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 297 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 296);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 302 "MSV.l"


void DeleteSingleLineComment(void)
{
    register int c;

	while((c=yyinput()) != '\n' && c!=EOF)
	{
	    // do nothing
    }
	++lineno;
}

void passStringConstant (void)
{//modified by yubin 2014/2/25，处理char*字符串中的转义字符，第一个if分支处理没有转义字符的情况，下面的分支处理有转义字符的情况
	int l = ( strlen( yytext ) - 2 );
	yylval.cString = new char[l+1];
	strncpy( yylval.cString, &yytext[1], l );
	int i;
	int j=0;//j用来记录转义字符的个数
	for(i=0;i+j<l;i=i+1)
	{
		if(yylval.cString[i+j]!='\\')
		{
			yylval.cString[i]=yylval.cString[i+j];
		}
		else if(yylval.cString[i+j+1]=='n')
		{
			yylval.cString[i]='\n';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='b')
		{
			yylval.cString[i]='\b';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='f')
		{
			yylval.cString[i]='\f';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='r')
		{
			yylval.cString[i]='\r';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='t')
		{
			yylval.cString[i]='\t';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='\'')
		{
			yylval.cString[i]='\'';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='\"')
		{
			yylval.cString[i]='\"';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='\\')
		{
			yylval.cString[i]='\\';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='0')
		{
			yylval.cString[i]='\0';
			j=j+1;
		}
		else//是转义字符，但是不是上面的一些转义字符，暂时什么也不做
		{
		
		}	
	}
	yylval.cString[i] = '\0';
}