#line 2 "lex.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

<<<<<<< HEAD
#define YY_NUM_RULES 161
#define YY_END_OF_BUFFER 162
static yyconst short int yy_accept[421] =
    {   0,
        0,    0,    0,    0,  162,  156,  155,  154,  106,  156,
      128,  113,   43,  156,  121,  122,  111,  109,  127,  110,
       97,  112,  147,  147,   17,   42,  101,   98,  102,  146,
      146,  146,  123,  124,  114,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  125,  132,  126,  117,
      157,  158,  157,  157,  155,  105,    0,  150,    0,    0,
        0,  119,    1,  153,  108,  151,  147,    0,    0,  100,
        0,  107,  115,  103,  118,  104,  116,  146,  146,  146,
      146,  141,  146,  146,  146,  146,  146,  146,  146,  146,

      146,  146,  146,  146,  146,  146,   33,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,  146,   27,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  133,  146,    3,  146,  129,  146,  146,
      146,  146,  146,  131,  146,  146,  146,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  146,  146,  146,
        9,  160,    0,  150,    0,    0,  152,  152,  151,  148,
        0,  149,  120,   99,  146,  146,   76,  146,   15,    2,
      146,  146,  146,  146,  146,  146,  146,  135,   62,  146,
      146,  146,  146,  146,   70,  146,  146,  146,  146,  146,

        5,  146,  146,  146,   30,  146,  146,  146,  146,  139,
      146,  146,  146,   44,  146,  146,  146,   25,  146,   71,
      146,  146,  146,  146,  146,  146,   75,  146,   10,  146,
      138,  146,  146,  146,  146,  146,  146,  146,   61,  146,
      146,   16,  146,  146,  146,  146,  146,   63,  146,  146,
      146,  146,  146,  146,  146,  146,  146,  130,  159,   89,
      140,   65,   64,   66,  146,  146,   94,   59,   47,   68,
      146,  146,  146,   29,  146,  146,  146,   77,  146,  146,
      146,  146,  146,   79,  146,  146,  146,  145,  146,  146,
        7,   51,  146,   14,   78,  146,   49,  146,  146,   80,

       13,   11,  146,  146,  146,  134,  146,  146,  146,  146,
      146,  136,  146,   67,  146,    4,   73,  146,  146,  146,
      146,  146,  146,   52,   69,   28,  146,   23,  146,  146,
      146,   50,  146,  146,   74,    8,   93,  146,  146,  146,
        6,  146,  146,   24,  146,   85,   84,   48,   60,   83,
       87,   86,   26,   82,  146,   38,   81,   72,  146,  146,
      146,  146,  146,  146,  146,  146,   58,  146,  146,  146,
      146,  146,  146,  146,  146,  146,  146,   31,   22,  146,
       35,  146,   32,  146,   19,  146,   18,   91,   88,  146,
      144,   37,  146,   40,  146,   34,  146,   96,  142,   57,

       53,   54,   56,   45,   55,   21,   92,   90,  146,   12,
       95,   36,  146,   46,  137,   39,  146,   20,  143,    0
=======
#define YY_NUM_RULES 119
#define YY_END_OF_BUFFER 120
static yyconst short int yy_accept[318] =
    {   0,
        0,    0,    0,    0,  120,  114,  113,  112,   66,  114,
       88,   73,   42,  114,   81,   82,   71,   69,   87,   70,
       57,   72,  105,  105,   17,   41,   61,   58,   62,  104,
      104,  104,   83,   84,   74,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,   85,   92,   86,   77,
      115,  116,  115,  115,  113,   65,    0,  108,    0,    0,
        0,   79,    1,  111,   68,  109,  105,    0,    0,   60,
        0,   67,   75,   63,   78,   64,   76,  104,  104,  104,
      104,  101,  104,  104,  104,  104,  104,  104,  104,  104,

       33,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,   27,  104,  104,  104,  104,  104,   93,  104,
        3,  104,   89,  104,  104,  104,  104,   91,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,    9,  118,    0,  108,    0,    0,  110,  110,  109,
      106,    0,  107,   80,   59,  104,  104,   15,    2,  104,
      104,  104,  104,   95,  104,  104,  104,  104,  104,  104,
      104,    5,  104,   30,  104,  104,   99,  104,  104,   43,
      104,   25,  104,  104,  104,  104,  104,  104,   10,  104,
       98,  104,  104,  104,  104,  104,  104,  104,   16,  104,

      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
       90,  117,   50,  100,  104,  104,   54,   46,  104,  104,
      104,   29,  104,  104,  104,  104,  104,  104,  104,    7,
      104,   14,   48,   13,   11,  104,  104,  104,   94,  104,
      104,  104,  104,   96,  104,    4,  104,  104,  104,   28,
      104,   23,  104,  104,  104,   49,  104,  104,    8,   53,
      104,  104,  104,    6,  104,  104,   24,   47,   26,  104,
       38,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,   31,   22,  104,   35,  104,   32,  104,   19,
      104,   18,   51,  104,   37,  104,   40,  104,   34,  104,

       56,  102,   44,   21,   52,  104,   12,   55,   36,  104,
       45,   97,   39,  104,   20,  103,    0
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   28,
       29,   29,   30,   29,   29,   31,   29,   32,   33,   29,
       29,   29,   29,   29,   34,   29,   29,   35,   29,   29,
       36,   37,   38,   39,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
       65,   29,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[70] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        1,    1,    1,    1,    1,    4,    4,    4,    2,    2,
        2,    2,    2,    2,    2,    1,    1,    1,    1,    2,
        4,    4,    4,    4,    4,    4,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[323] =
    {   0,
        0,    0,   67,   68,  205,  983,  195,  983,  169,   67,
      983,  983,  983,  152,  983,  983,  983,  983,  983,  157,
      983,   60,   57,   67,  155,  983,   73,  148,   58,   79,
       81,   86,  117,  983,  983,   88,   90,   95,  104,  108,
      113,   99,   97,  110,  138,  147,  115,  156,  126,  158,
      161,  175,  179,  171,  166,  183,  983,   85,  983,  983,
      983,  983,  132,  114,  139,  983,   85,  983,  199,  129,
      237,  983,  983,  983,  983,  188,  195,    0,  232,  983,
       88,  983,  983,   79,  983,  983,  983,  106,  191,  224,
      230,  983,  243,  245,  249,  251,  253,  257,  261,  265,

      267,  273,  281,  289,  283,  294,  296,  298,  300,  303,
      306,  308,  310,  314,  320,  323,  325,  327,  333,  335,
      339,  342,  344,  348,  353,  356,  361,  359,  368,  363,
      370,  372,  374,  381,  386,  376,  392,  395,  407,  404,
      414,   26,  983,   60,  126,  132,  430,  983,   69,  417,
        0,  427,  419,  983,  983,  432,  446,  441,  449,  451,
      454,  459,  461,  463,  466,  472,  479,  482,  486,  489,
      491,  493,  497,  501,  503,  506,  510,  512,  516,  520,
      524,  527,  532,  534,  538,  540,  543,  545,  547,  550,
      554,  556,  562,  564,  566,  568,  570,  575,  580,  583,

      585,  589,  591,  594,  596,  598,  600,  602,  609,  614,
      983,  983,  618,  621,  633,  636,  638,  640,  642,  644,
      648,  650,  652,  654,  657,  659,  661,  663,  665,  669,
      671,  675,  677,  682,  686,  690,  692,  699,  703,  707,
      709,  713,  715,  717,  719,  721,  723,  725,  727,  734,
      740,  742,  746,  755,  752,  759,  761,  763,  765,  767,
      769,  771,  773,  775,  777,  786,  790,  792,  798,  800,
      803,  807,  809,  811,  814,  818,  822,  825,  827,  833,
      831,  836,  838,  840,  842,  844,  846,  849,  853,  863,
      866,  868,  870,  873,  875,  878,  880,  882,  884,  888,

      890,  892,  895,  897,  899,  901,  903,  905,  910,  913,
      915,  918,  920,  922,  924,  930,  983,  967,  971,  975,
      978,   71
    } ;

static yyconst short int yy_def[323] =
    {   0,
      317,    1,  318,  318,  317,  317,  317,  317,  317,  319,
      317,  317,  317,  320,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  321,
      321,  321,  317,  317,  317,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  319,  317,  319,  317,
      317,  317,  317,  317,  317,  317,  317,  322,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  321,  321,  321,
      321,  317,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  317,  317,  317,  319,  319,  319,  317,  317,  317,
      322,  317,  317,  317,  317,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      317,  317,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,    0,  317,  317,  317,
      317,  317
    } ;

static yyconst short int yy_nxt[1053] =
    {   0,
        6,    7,    8,    9,   10,   11,    6,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   30,   31,   30,   30,
       30,   32,   30,   30,   30,   33,    6,   34,   35,   30,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   30,
       45,   46,   47,   48,   49,   50,   30,   51,   52,   53,
       54,   55,   56,   30,   30,   57,   58,   59,   60,   62,
       62,   68,   73,   76,  151,   77,   77,   74,  148,   63,
       63,   86,   87,   76,   75,   77,   77,  212,   81,   68,
       82,   78,  211,   64,   64,   83,   84,   89,   89,   89,

       89,   79,  155,   69,   89,   89,   89,   89,   89,   89,
       90,   79,  154,   89,   89,   89,   89,   89,   89,   91,
       78,   69,   89,   89,   89,   89,   89,   89,   89,   89,
       68,   89,   89,   89,   89,   97,   68,  112,  148,   93,
       65,   94,   98,  111,   89,   89,  144,   96,   99,  143,
       95,  142,  100,  105,   92,  113,   89,   89,  101,  102,
      103,  106,   69,  114,  107,   89,   89,  108,   69,  118,
      109,  104,   85,  110,   89,   89,   89,   89,   80,   89,
       89,   72,  115,  121,   89,   89,  122,  123,   71,   89,
       89,  116,   66,   89,   89,  117,   65,   89,   89,  119,

      120,   89,   89,  145,  317,  127,  150,  150,  146,   89,
       89,   76,  124,   77,   77,  125,  128,  146,  126,  129,
      139,  317,  140,  130,  138,  131,  135,  136,  317,  132,
      141,  317,   79,  317,  133,  147,  137,  134,  317,   79,
      146,   70,   89,   89,  146,  152,  149,  152,   89,   89,
      153,  153,  146,  317,  156,   70,  146,  317,  146,  317,
      157,   89,   89,   89,   89,  146,  317,   89,   89,   89,
       89,   89,   89,   70,  317,   89,   89,  317,   70,   89,
       89,  317,   70,   89,   89,   89,   89,  317,  159,  160,
       70,   89,   89,  317,   70,  161,   70,  163,  152,   89,

       89,   89,   89,   70,  317,  158,  165,   89,   89,  317,
      164,  162,   89,   89,   89,   89,   89,   89,   89,   89,
      317,   89,   89,  166,   89,   89,   89,   89,   89,   89,
      317,  167,   89,   89,  171,  317,  168,  169,   89,   89,
      175,   89,   89,   89,   89,   89,   89,  172,  170,  317,
      173,   89,   89,   89,   89,  174,  176,   89,   89,  178,
       89,   89,   89,   89,  181,  177,   89,   89,  317,  179,
      317,   89,   89,  180,   89,   89,  182,   89,   89,   89,
       89,   89,   89,  183,  184,  317,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,  187,  188,  185,   89,

       89,  186,  189,  192,   89,   89,  317,  190,  317,  197,
       89,   89,  317,   89,   89,  191,  193,  194,  198,  317,
      195,  196,   89,   89,  199,   89,   89,  317,  203,  201,
      202,  200,   89,   89,  145,  150,  150,  153,  153,  146,
      152,  317,  152,  205,  317,  153,  153,  317,  146,  317,
       89,   89,  204,  206,  207,  208,  317,  209,  213,   89,
       89,   79,  210,  317,   89,   89,  147,   89,   89,   89,
       89,  146,   89,   89,  317,  146,  214,   89,   89,   89,
       89,   89,   89,  146,   89,   89,  317,  146,  317,  146,
       89,   89,  317,  152,  216,  317,  146,   89,   89,  215,

       89,   89,  317,  217,   89,   89,  219,   89,   89,   89,
       89,   89,   89,  317,  220,   89,   89,  317,  218,   89,
       89,   89,   89,  222,   89,   89,  317,  221,   89,   89,
       89,   89,  317,  225,   89,   89,  317,  227,   89,   89,
      317,  223,   89,   89,  224,   89,   89,  317,  229,  226,
       89,   89,   89,   89,  317,  228,   89,   89,   89,   89,
      317,   89,   89,   89,   89,   89,   89,  317,   89,   89,
      317,  230,   89,   89,   89,   89,  231,  317,  234,  232,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
      238,  233,  239,   89,   89,  236,  237,  235,   89,   89,

      240,   89,   89,   89,   89,  317,  241,   89,   89,   89,
       89,  244,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,  317,  245,  242,  317,  243,   89,   89,  317,
      246,  247,   89,   89,  317,  251,   89,   89,  252,   89,
       89,  317,  250,  248,  249,  256,  254,  317,  255,  317,
      253,   89,   89,  257,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,  317,  258,   89,   89,   89,   89,
       89,   89,   89,   89,  317,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,  317,  260,   89,   89,   89,
       89,  317,  259,   89,   89,   89,   89,  262,  317,  263,

       89,   89,  261,  267,   89,   89,  317,  269,   89,   89,
       89,   89,  317,  265,  266,  317,  264,   89,   89,  317,
      268,   89,   89,  317,  270,   89,   89,   89,   89,  317,
      271,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,  274,  317,  276,
      272,  273,   89,   89,  317,  275,  317,  277,   89,   89,
       89,   89,  317,  279,   89,   89,  317,  281,  317,  282,
       89,   89,  278,   89,   89,  317,  280,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,  317,  283,  284,

      317,  285,  317,  286,   89,   89,  317,  288,   89,   89,
       89,   89,  317,  291,  317,  290,   89,   89,   89,   89,
      289,   89,   89,  317,  287,   89,   89,   89,   89,   89,
       89,  317,   89,   89,  317,  292,   89,   89,  317,  293,
       89,   89,  317,   89,   89,   89,   89,  317,  294,   89,
       89,   89,   89,  296,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,  295,   89,   89,  317,
      302,   89,   89,  317,  297,  298,  317,  299,  301,  303,
      300,   89,   89,  305,   89,   89,   89,   89,   89,   89,
      304,   89,   89,   89,   89,  306,   89,   89,   89,   89,

       89,   89,   89,   89,  317,  307,   89,   89,   89,   89,
       89,   89,  308,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,  317,  312,  310,   89,   89,
      309,   89,   89,   89,   89,  311,   89,   89,   89,   89,
       89,   89,   89,   89,  317,  314,  317,  313,   89,   89,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  316,  315,   61,   61,   61,
       61,   67,   67,   67,   67,   70,   70,  317,   70,   88,
      317,   88,    5,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,

      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317
    } ;

static yyconst short int yy_chk[1053] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,   10,   22,   23,  322,   23,   23,   22,  149,    3,
        4,   29,   29,   24,   22,   24,   24,  144,   27,   67,
       27,   23,  142,    3,    4,   27,   27,   30,   30,   31,

       31,   23,   84,   10,   32,   32,   36,   36,   37,   37,
       31,   24,   81,   38,   38,   43,   43,   42,   42,   32,
       23,   67,   39,   39,   88,   88,   40,   40,   44,   44,
      145,   41,   41,   47,   47,   38,  146,   43,   70,   36,
       65,   36,   38,   42,   49,   49,   64,   37,   39,   63,
       36,   58,   39,   41,   33,   44,   45,   45,   39,   40,
       40,   41,  145,   44,   41,   46,   46,   41,  146,   47,
       41,   40,   28,   41,   48,   48,   50,   50,   25,   51,
       51,   20,   45,   49,   55,   55,   49,   49,   14,   54,
       54,   46,    9,   52,   52,   46,    7,   53,   53,   48,

       48,   56,   56,   69,    5,   51,   76,   76,   69,   89,
       89,   77,   50,   77,   77,   50,   51,   69,   50,   52,
       55,    0,   56,   52,   54,   52,   53,   53,    0,   52,
       56,    0,   76,    0,   52,   69,   53,   52,    0,   77,
       69,   71,   90,   90,   69,   79,   71,   79,   91,   91,
       79,   79,   69,    0,   90,   71,   69,    0,   69,    0,
       91,   93,   93,   94,   94,   69,    0,   95,   95,   96,
       96,   97,   97,   71,    0,   98,   98,    0,   71,   99,
       99,    0,   71,  100,  100,  101,  101,    0,   94,   95,
       71,  102,  102,    0,   71,   96,   71,   98,   79,  103,

      103,  105,  105,   71,    0,   93,   99,  104,  104,    0,
       98,   97,  106,  106,  107,  107,  108,  108,  109,  109,
        0,  110,  110,  100,  111,  111,  112,  112,  113,  113,
        0,  102,  114,  114,  105,    0,  103,  104,  115,  115,
      109,  116,  116,  117,  117,  118,  118,  106,  104,    0,
      107,  119,  119,  120,  120,  108,  110,  121,  121,  112,
      122,  122,  123,  123,  115,  111,  124,  124,    0,  114,
        0,  125,  125,  114,  126,  126,  116,  128,  128,  127,
      127,  130,  130,  117,  118,    0,  129,  129,  131,  131,
      132,  132,  133,  133,  136,  136,  124,  125,  120,  134,

      134,  122,  125,  127,  135,  135,    0,  125,    0,  130,
      137,  137,    0,  138,  138,  126,  127,  127,  131,    0,
      127,  129,  140,  140,  132,  139,  139,    0,  136,  134,
      135,  133,  141,  141,  147,  150,  150,  153,  153,  147,
      152,    0,  152,  138,    0,  152,  152,    0,  147,    0,
      156,  156,  137,  138,  138,  139,    0,  140,  156,  158,
      158,  150,  141,    0,  157,  157,  147,  159,  159,  160,
      160,  147,  161,  161,    0,  147,  157,  162,  162,  163,
      163,  164,  164,  147,  165,  165,    0,  147,    0,  147,
      166,  166,    0,  152,  161,    0,  147,  167,  167,  160,

      168,  168,    0,  162,  169,  169,  165,  170,  170,  171,
      171,  172,  172,    0,  165,  173,  173,    0,  163,  174,
      174,  175,  175,  167,  176,  176,    0,  166,  177,  177,
      178,  178,    0,  170,  179,  179,    0,  173,  180,  180,
        0,  168,  181,  181,  169,  182,  182,    0,  176,  171,
      183,  183,  184,  184,    0,  175,  185,  185,  186,  186,
        0,  187,  187,  188,  188,  189,  189,    0,  190,  190,
        0,  178,  191,  191,  192,  192,  179,    0,  184,  181,
      193,  193,  194,  194,  195,  195,  196,  196,  197,  197,
      188,  183,  190,  198,  198,  186,  187,  185,  199,  199,

      192,  200,  200,  201,  201,    0,  193,  202,  202,  203,
      203,  196,  204,  204,  205,  205,  206,  206,  207,  207,
      208,  208,    0,  197,  194,    0,  195,  209,  209,    0,
      198,  200,  210,  210,    0,  203,  213,  213,  204,  214,
      214,    0,  202,  200,  201,  208,  206,    0,  207,    0,
      205,  215,  215,  209,  216,  216,  217,  217,  218,  218,
      219,  219,  220,  220,    0,  210,  221,  221,  222,  222,
      223,  223,  224,  224,    0,  225,  225,  226,  226,  227,
      227,  228,  228,  229,  229,    0,  216,  230,  230,  231,
      231,    0,  215,  232,  232,  233,  233,  220,    0,  221,

      234,  234,  219,  226,  235,  235,    0,  228,  236,  236,
      237,  237,    0,  224,  225,    0,  223,  238,  238,    0,
      227,  239,  239,    0,  229,  240,  240,  241,  241,    0,
      231,  242,  242,  243,  243,  244,  244,  245,  245,  246,
      246,  247,  247,  248,  248,  249,  249,  238,    0,  241,
      236,  237,  250,  250,    0,  240,    0,  242,  251,  251,
      252,  252,    0,  245,  253,  253,    0,  248,    0,  249,
      255,  255,  243,  254,  254,    0,  247,  256,  256,  257,
      257,  258,  258,  259,  259,  260,  260,  261,  261,  262,
      262,  263,  263,  264,  264,  265,  265,    0,  251,  253,

        0,  254,    0,  255,  266,  266,    0,  258,  267,  267,
      268,  268,    0,  263,    0,  262,  269,  269,  270,  270,
      261,  271,  271,    0,  257,  272,  272,  273,  273,  274,
      274,    0,  275,  275,    0,  265,  276,  276,    0,  266,
      277,  277,    0,  278,  278,  279,  279,    0,  270,  281,
      281,  280,  280,  273,  282,  282,  283,  283,  284,  284,
      285,  285,  286,  286,  287,  287,  272,  288,  288,    0,
      279,  289,  289,    0,  274,  275,    0,  276,  278,  280,
      277,  290,  290,  282,  291,  291,  292,  292,  293,  293,
      281,  294,  294,  295,  295,  285,  296,  296,  297,  297,

      298,  298,  299,  299,    0,  287,  300,  300,  301,  301,
      302,  302,  289,  303,  303,  304,  304,  305,  305,  306,
      306,  307,  307,  308,  308,    0,  298,  294,  309,  309,
      291,  310,  310,  311,  311,  296,  312,  312,  313,  313,
      314,  314,  315,  315,    0,  306,    0,  300,  316,  316,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  314,  310,  318,  318,  318,
      318,  319,  319,  319,  319,  320,  320,    0,  320,  321,
        0,  321,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,

      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "MSV.l"
#define INITIAL 0
#line 2 "MSV.l"
#include "function.h"
#include <string.h> // strcpy, strncpy
#include <math.h>
#include <io.h>     // isatty.h>
#include "MyMap.h"
#include "SyntaxNode.h"




extern CMAP g_StructNameMap;
int lineno=1;

// For some reason isatty is called _isatty in Visual C++
#ifdef MSVC
#define isatty _isatty
#endif

// Forward declarations for include files
class CSyntaxNode;
class Symbol;
class SymbolTable;

// Make sure our variables get created
#define  _LEX_CPP_
//#include "lex.h"
//#include "lexSymbol.h"
#include "parse.cpp.h"

// The yywrap and error functions are declared by the caller
extern "C" int yywrap();
extern void error( char *cFormat, ... );
extern 

void DeleteSingleLineComment (void);
void passStringConstant (void);

#define comment 1

/*
\b 退格
\f 走纸换页
\n 换行
\r 回车
\t 横向跳格 (Ctrl-I)
\' 单引号
\" 双引号
\\反斜杠
*/
#line 752 "lex.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 68 "MSV.l"


#line 902 "lex.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 318 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 983 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 70 "MSV.l"
BEGIN comment;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 72 "MSV.l"
{return AND;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 73 "MSV.l"
{return OR;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 74 "MSV.l"
{return SKIP;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 75 "MSV.l"
{return FINAL;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 76 "MSV.l"
{return EMPTY;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 77 "MSV.l"
{return HALT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 78 "MSV.l"
{return AWAIT;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 79 "MSV.l"
{return PARALLEL;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 80 "MSV.l"
{return PROJECTION;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 81 "MSV.l"
{return NEXT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 82 "MSV.l"
{return W_NEXT;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 83 "MSV.l"
{return MORE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 84 "MSV.l"
{return KEEP;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 85 "MSV.l"
{return ALWAYS;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 86 "MSV.l"
{return SOMETIMES;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 87 "MSV.l"
{return COLON;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 88 "MSV.l"
{return EXIST;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 89 "MSV.l"
{return DEFINE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 90 "MSV.l"
{return FUNCTION;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 91 "MSV.l"
{return STRUCT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 92 "MSV.l"
{return UNION;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 93 "MSV.l"
{return MY_TRUE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 94 "MSV.l"
{return MY_FALSE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 96 "MSV.l"
{return LENGTH;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 97 "MSV.l"
{return FRAME;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 98 "MSV.l"
{return IF;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 99 "MSV.l"
{return THEN;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 100 "MSV.l"
{return ELSE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 101 "MSV.l"
{return FOR;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 102 "MSV.l"
{return TIMES;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 103 "MSV.l"
{return WHILE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 104 "MSV.l"
{return DO;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 105 "MSV.l"
{return REPEAT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 106 "MSV.l"
{return UNTIL;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 107 "MSV.l"
{return DISPLAY;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 108 "MSV.l"
{return DISPLAY;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 109 "MSV.l"
{return REQUEST;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 110 "MSV.l"
{return REQUEST;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 111 "MSV.l"
{return PREFIX;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 113 "MSV.l"
<<<<<<< HEAD
{return COLON;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 115 "MSV.l"
{return CHOP;}
=======
{return CHOP;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 114 "MSV.l"
{return ADDRESS;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 116 "MSV.l"
<<<<<<< HEAD
{return ADDRESS;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 118 "MSV.l"
{return INTDECLARATION;}//  added by Jane 2012-05-21
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 119 "MSV.l"
{return STRDECLARATION;}//STRVARIABLE  added by Jane 2012-05-21
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 120 "MSV.l"
{return POINTERDECLARATION;}//POINTER  added by Jane 2012-05-21
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 121 "MSV.l"
{return CHARDECLARATION;}//CHARVARIABLE  added by Jane 2012-05-21 
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 122 "MSV.l"
{return FLOATDECLARATION;}//FLOATVARIABLE  added by Jane 2012-05-21
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 123 "MSV.l"
{return LISTDECLARATION;}//LISTVARIABLE  added by Jane 2012-05-21
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 124 "MSV.l"
{return VOIDDECLARATION;}
=======
{return INTDECLARATION;}//  added by Jane 2012-05-21
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 117 "MSV.l"
{return STRDECLARATION;}//STRVARIABLE  added by Jane 2012-05-21
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 118 "MSV.l"
{return POINTERDECLARATION;}//POINTER  added by Jane 2012-05-21
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 119 "MSV.l"
{return CHARDECLARATION;}//CHARVARIABLE  added by Jane 2012-05-21 
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 120 "MSV.l"
{return FLOATDECLARATION;}//FLOATVARIABLE  added by Jane 2012-05-21
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 121 "MSV.l"
{return LISTDECLARATION;}//LISTVARIABLE  added by Jane 2012-05-21
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 122 "MSV.l"
{return VOIDDECLARATION;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 125 "MSV.l"
{return FILEDECLARATION;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 126 "MSV.l"
<<<<<<< HEAD
{return		STRFUNCHEAD;}
=======
{return EXTERN;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 127 "MSV.l"
<<<<<<< HEAD
{return		STRFUNCTAIL;}
=======
{return SWITCH;}//add by yubin 2015-3-23
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 128 "MSV.l"
<<<<<<< HEAD
{return		STRFUNCCAT;}
=======
{return BREAK;}//add by yubin 2015-3-23
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 129 "MSV.l"
<<<<<<< HEAD
{return		STRFUNCCMP;}
=======
{return CASE;}//add by yubin 2015-3-23
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 130 "MSV.l"
<<<<<<< HEAD
{return		STRFUNCLEN;}
=======
{return DEFAULT;}//add by yubin 2015-3-23
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 131 "MSV.l"
<<<<<<< HEAD
{return		STRFUNCCPY;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 132 "MSV.l"
{return     SIZEOF;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 135 "MSV.l"
{return ROUND;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 136 "MSV.l"
{return CEIL;}
=======
{return RETURN;}//2015-4-13,add by yubin
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 133 "MSV.l"
{return DOT;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 134 "MSV.l"
{return EQ;}     //比较相等符号 “=”
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 135 "MSV.l"
{return ASS_P;}   //赋值符号已修改为“<==”
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 137 "MSV.l"
<<<<<<< HEAD
{return FLOOR;}
=======
{return ASS_N;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 139 "MSV.l"
<<<<<<< HEAD
{return SIN;}
=======
{return LT;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 140 "MSV.l"
<<<<<<< HEAD
{return COS;}
=======
{return GT;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 141 "MSV.l"
<<<<<<< HEAD
{return TAN;}
=======
{return LE;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 142 "MSV.l"
<<<<<<< HEAD
{return ASIN;}
=======
{return GE;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 143 "MSV.l"
<<<<<<< HEAD
{return ACOS;}
=======
{return NE;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 144 "MSV.l"
<<<<<<< HEAD
{return ATAN;}
=======
{return NEGATION;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 145 "MSV.l"
<<<<<<< HEAD
{return SINH;}
=======
{return PBEGIN;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 146 "MSV.l"
<<<<<<< HEAD
{return COSH;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 147 "MSV.l"
{return TANH;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 148 "MSV.l"
{return EXP;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 149 "MSV.l"
{return LOG;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 150 "MSV.l"
{return LOG10;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 151 "MSV.l"
{return SQRT;}
=======
{return PEND;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 148 "MSV.l"
{return ADD;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 149 "MSV.l"
{return SUB;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 150 "MSV.l"
{return MUL;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 151 "MSV.l"
{return DIV;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 152 "MSV.l"
{return MOD;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 153 "MSV.l"
<<<<<<< HEAD
{return ATAN2;}
=======
{return CON;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 154 "MSV.l"
<<<<<<< HEAD
{return POW;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 156 "MSV.l"
{return ABS;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 157 "MSV.l"
{return FABS;}
=======
{return LST;}//左移 left shift
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 155 "MSV.l"
{return RST;}//右移 right shift
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 156 "MSV.l"
{return BNE;}//按位非 bit negation
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 158 "MSV.l"
<<<<<<< HEAD
{return LABS;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 160 "MSV.l"
{return FMOD;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 161 "MSV.l"
{return MODF;}
=======
{return PROPIMPLY;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 159 "MSV.l"
{return IMPLY;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 160 "MSV.l"
{return IFF;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 162 "MSV.l"
<<<<<<< HEAD
{return LDEXP;}
=======
{return OPEN_PAR;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 163 "MSV.l"
<<<<<<< HEAD
{return FREXP;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 165 "MSV.l"
{return FOPEN;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 166 "MSV.l"
{return FGETS;} 
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 167 "MSV.l"
{return FGETC;} 
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 168 "MSV.l"
{return FPUTS;} 
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 169 "MSV.l"
{return FPUTC;} 
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 170 "MSV.l"
{return FCLOSE;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 171 "MSV.l"
{return FILEDECLARATION;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 172 "MSV.l"
{return SYSTEM;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 173 "MSV.l"
{return EXTERN;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 174 "MSV.l"
{return SWITCH;}//add by yubin 2015-3-23
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 175 "MSV.l"
{return BREAK;}//add by yubin 2015-3-23
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 176 "MSV.l"
{return CASE;}//add by yubin 2015-3-23
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 177 "MSV.l"
{return DEFAULT;}//add by yubin 2015-3-23
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 178 "MSV.l"
{return RETURN;}//2015-4-13,add by yubin
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 180 "MSV.l"
{return DOT;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 181 "MSV.l"
{return EQ;}     //比较相等符号 “=”
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 182 "MSV.l"
{return ASS_P;}   //赋值符号已修改为“<==”
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 184 "MSV.l"
{return ASS_N;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 186 "MSV.l"
{return LT;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 187 "MSV.l"
{return GT;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 188 "MSV.l"
{return LE;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 189 "MSV.l"
{return GE;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 190 "MSV.l"
{return NE;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 191 "MSV.l"
{return NEGATION;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 192 "MSV.l"
{return PBEGIN;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 193 "MSV.l"
{return PEND;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 195 "MSV.l"
{return ADD;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 196 "MSV.l"
{return SUB;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 197 "MSV.l"
{return MUL;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 198 "MSV.l"
{return DIV;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 199 "MSV.l"
{return MOD;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 200 "MSV.l"
{return CON;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 201 "MSV.l"
{return LST;}//左移 left shift
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 202 "MSV.l"
{return RST;}//右移 right shift
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 203 "MSV.l"
{return BNE;}//按位非 bit negation
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 205 "MSV.l"
{return PROPIMPLY;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 206 "MSV.l"
{return IMPLY;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 207 "MSV.l"
{return IFF;}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 209 "MSV.l"
{return OPEN_PAR;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 210 "MSV.l"
{return CLOSE_PAR;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 211 "MSV.l"
{return OPEN_MPAR;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 212 "MSV.l"
{return CLOSE_MPAR;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 213 "MSV.l"
{return OPEN_BPAR;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 214 "MSV.l"
{return CLOSE_BPAR;}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 215 "MSV.l"
{return COMMA;}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 216 "MSV.l"
{return CHOPSTAR;}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 219 "MSV.l"
{return OVER;}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 220 "MSV.l"
{return CYLINDER;}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 221 "MSV.l"
{return OVEREP;}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 223 "MSV.l"
{return	INTER_OR;}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 224 "MSV.l"
{return NON_DETERMINED;}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 226 "MSV.l"
{return PROCESS;}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 227 "MSV.l"
{return CHANNEL;}
=======
{return CLOSE_PAR;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 164 "MSV.l"
{return OPEN_MPAR;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 165 "MSV.l"
{return CLOSE_MPAR;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 166 "MSV.l"
{return OPEN_BPAR;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 167 "MSV.l"
{return CLOSE_BPAR;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 168 "MSV.l"
{return COMMA;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 169 "MSV.l"
{return CHOPSTAR;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 172 "MSV.l"
{return OVER;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 173 "MSV.l"
{return CYLINDER;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 174 "MSV.l"
{return OVEREP;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 176 "MSV.l"
{return	INTER_OR;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 93:
YY_RULE_SETUP
<<<<<<< HEAD
#line 228 "MSV.l"
{return SEND;}
=======
#line 177 "MSV.l"
{return NON_DETERMINED;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 94:
YY_RULE_SETUP
<<<<<<< HEAD
#line 229 "MSV.l"
{return RECEIVE;}
=======
#line 179 "MSV.l"
{return PROCESS;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 95:
YY_RULE_SETUP
<<<<<<< HEAD
#line 230 "MSV.l"
{return PUT;}
=======
#line 180 "MSV.l"
{return CHANNEL;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 96:
YY_RULE_SETUP
<<<<<<< HEAD
#line 231 "MSV.l"
{return GET;}
=======
#line 181 "MSV.l"
{return SEND;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 97:
YY_RULE_SETUP
<<<<<<< HEAD
#line 233 "MSV.l"
{return POINTERNULL;}
=======
#line 182 "MSV.l"
{return RECEIVE;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 98:
YY_RULE_SETUP
<<<<<<< HEAD
#line 234 "MSV.l"
{return ARRAY;}
=======
#line 183 "MSV.l"
{return PUT;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 99:
YY_RULE_SETUP
<<<<<<< HEAD
#line 236 "MSV.l"
{return SIGNED;}
=======
#line 184 "MSV.l"
{return GET;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 100:
YY_RULE_SETUP
<<<<<<< HEAD
#line 237 "MSV.l"
{return UNSIGNED;}
=======
#line 186 "MSV.l"
{return POINTERNULL;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 101:
YY_RULE_SETUP
<<<<<<< HEAD
#line 239 "MSV.l"
{return MALLOC;}//malloc相关
=======
#line 187 "MSV.l"
{return ARRAY;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 102:
YY_RULE_SETUP
<<<<<<< HEAD
#line 240 "MSV.l"
{return FREE;}
=======
#line 189 "MSV.l"
{return SIGNED;}
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
	YY_BREAK
case 103:
YY_RULE_SETUP
<<<<<<< HEAD
#line 243 "MSV.l"
=======
#line 190 "MSV.l"
{return UNSIGNED;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 194 "MSV.l"
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
{
			   yylval.cString=new char[strlen(yytext)+1];
			   strcpy(yylval.cString,yytext);
               
			   if(!g_StructNameMap.find(yytext))
			   {
			       return ID;
			   }
			   else
			   {
                   return STRUCT_TYPE;
			   }
		}
	YY_BREAK
<<<<<<< HEAD
case 147:
YY_RULE_SETUP
#line 256 "MSV.l"
=======
case 105:
YY_RULE_SETUP
#line 207 "MSV.l"
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
{    
               yylval.nInteger=atoi(yytext);
               return INTLITERAL;
		 }
	YY_BREAK
<<<<<<< HEAD
case 148:
YY_RULE_SETUP
#line 260 "MSV.l"
=======
case 106:
YY_RULE_SETUP
#line 211 "MSV.l"
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
{    
               int decValue;//int，保存16进制对应的十进制数
			   sscanf(yytext,"%x",&decValue);//将16进制字符串转成10进制数
			   yylval.nInteger=decValue;//将10进制数赋给yytext
               return INTLITERAL;
			}
	YY_BREAK
<<<<<<< HEAD
case 149:
YY_RULE_SETUP
#line 266 "MSV.l"
=======
case 107:
YY_RULE_SETUP
#line 217 "MSV.l"
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
{
               char* result=NULL;
			   result=strtok(yytext, "e");
			   int iVal;
			   float fVal;
			   sscanf(result, "%f", &fVal);
			   while(result!=NULL)
			   {
			      sscanf(result, "%d", &iVal);
				  result = strtok(NULL, "e");
				}

               yylval.floatval = fVal*pow(10, iVal); 
			   return FLOATLITERAL;
			}
	YY_BREAK
<<<<<<< HEAD
case 150:
YY_RULE_SETUP
#line 281 "MSV.l"
=======
case 108:
YY_RULE_SETUP
#line 232 "MSV.l"
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
{
               passStringConstant ();
			   return STRLITERAL;
         }
	YY_BREAK
<<<<<<< HEAD
case 151:
YY_RULE_SETUP
#line 286 "MSV.l"
=======
case 109:
YY_RULE_SETUP
#line 237 "MSV.l"
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
{		
				yylval. floatval = atof(yytext); 
				return FLOATLITERAL; 
		 }//Added by Jane 2012-05-21 
	YY_BREAK
<<<<<<< HEAD
case 152:
YY_RULE_SETUP
#line 290 "MSV.l"
=======
case 110:
YY_RULE_SETUP
#line 241 "MSV.l"
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
{//modified by yubin 2014/2/25，第一个if分支处理没有转义字符的情况，下面的分支处理有转义字符的情况
				if(yytext[1]!='\\')
				{
					yylval.character=yytext[1];
					return CHARLITERAL;
				}
				else if(yytext[2]=='n')
				{
					yylval.character='\n';
					return CHARLITERAL;
				}
				else if(yytext[2]=='b')
				{
					yylval.character='\b';
					return CHARLITERAL;
				}
				else if(yytext[2]=='f')
				{
					yylval.character='\f';
					return CHARLITERAL;
				}
				else if(yytext[2]=='r')
				{
					yylval.character='\r';
					return CHARLITERAL;
				}
				else if(yytext[2]=='t')
				{
					yylval.character='\t';
					return CHARLITERAL;
				}
				else if(yytext[2]=='\'')
				{
					yylval.character='\'';
					return CHARLITERAL;
				}
				else if(yytext[2]=='\"')
				{
					yylval.character='\"';
					return CHARLITERAL;
				}
				else if(yytext[2]=='\\')
				{
					yylval.character='\\';
					return CHARLITERAL;
				}
				else if(yytext[2]=='0')
				{
					yylval.character='\0';
					return CHARLITERAL;
				}
		}   //2013-4-22 add by YY[fixed]
	YY_BREAK
<<<<<<< HEAD
case 153:
YY_RULE_SETUP
#line 345 "MSV.l"
{DeleteSingleLineComment();}
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 346 "MSV.l"
{++lineno;}
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 347 "MSV.l"
{}
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 348 "MSV.l"
{return ERROR_TOKEN;}
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 350 "MSV.l"
{}
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 351 "MSV.l"
{++lineno;}
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 352 "MSV.l"
{error("EOF in comment");}
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 353 "MSV.l"
{BEGIN 0;}
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 355 "MSV.l"
ECHO;
	YY_BREAK
#line 2203 "lex.cpp"
=======
case 111:
YY_RULE_SETUP
#line 296 "MSV.l"
{DeleteSingleLineComment();}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 297 "MSV.l"
{++lineno;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 298 "MSV.l"
{}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 299 "MSV.l"
{return ERROR_TOKEN;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 301 "MSV.l"
{}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 302 "MSV.l"
{++lineno;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 303 "MSV.l"
{error("EOF in comment");}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 304 "MSV.l"
{BEGIN 0;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 306 "MSV.l"
ECHO;
	YY_BREAK
#line 1671 "lex.cpp"
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 318 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 318 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 317);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
<<<<<<< HEAD
#line 355 "MSV.l"
=======
#line 306 "MSV.l"
>>>>>>> c7006a97d3ea4c7cf74b3454279e96b7f30fe1d6


void DeleteSingleLineComment(void)
{
    register int c;

	while((c=yyinput()) != '\n' && c!=EOF)
	{
	    // do nothing
    }
	++lineno;
}

void passStringConstant (void)
{//modified by yubin 2014/2/25，处理char*字符串中的转义字符，第一个if分支处理没有转义字符的情况，下面的分支处理有转义字符的情况
	int l = ( strlen( yytext ) - 2 );
	yylval.cString = new char[l+1];
	strncpy( yylval.cString, &yytext[1], l );
	int i;
	int j=0;//j用来记录转义字符的个数
	for(i=0;i+j<l;i=i+1)
	{
		if(yylval.cString[i+j]!='\\')
		{
			yylval.cString[i]=yylval.cString[i+j];
		}
		else if(yylval.cString[i+j+1]=='n')
		{
			yylval.cString[i]='\n';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='b')
		{
			yylval.cString[i]='\b';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='f')
		{
			yylval.cString[i]='\f';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='r')
		{
			yylval.cString[i]='\r';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='t')
		{
			yylval.cString[i]='\t';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='\'')
		{
			yylval.cString[i]='\'';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='\"')
		{
			yylval.cString[i]='\"';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='\\')
		{
			yylval.cString[i]='\\';
			j=j+1;
		}
		else if(yylval.cString[i+j+1]=='0')
		{
			yylval.cString[i]='\0';
			j=j+1;
		}
		else//是转义字符，但是不是上面的一些转义字符，暂时什么也不做
		{
		
		}	
	}
	yylval.cString[i] = '\0';
}